server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/vehicledb?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 200111
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maxmum-pool-size : 20
      max-lifetime: 1800000
      idle-timeout: 30000
      connection-timeout: 30000
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 10
      min-idle: 0

file:
  path: D:\spingboot\uploads

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.example.spingboot.common.handler

jwt:
  secret: Audit2022
  validity: 1800000

aes:
  aes-key: ASDnme29804HUjkP